spring.application.name=spring-ai-fly-schedule

#Ollama ??
spring.ai.ollama.base-url=http://ollama.java21.net
spring.ai.ollama.chat.options.model=qwen2.5:latest
spring.ai.ollama.chat.options.temperature=0.0

Google Gemini ??
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.0 
spring.ai.google.genai.chat.options.max-output-tokens=256
spring.ai.google.genai.chat.options.top-p=0.9
spring.ai.google.genai.chat.options.top-k=40

logging.level.com.nhnacademy.aiflyschedule=DEBUG
logging.level.org.springframework.ai=DEBUG

data-go-kr.api.url=https://apis.data.go.kr/1613000/DmstcFlightNvgInfo
data-go-kr.api.service-key=${DATA_GO_KR_SERVICE_KEY}
